from functools import partial
from datasets import load_dataset
from .sandbox import DockerSandbox
from .verifiers import get_llm_response


docker_sandbox = DockerSandbox()

def answer_validate(llm_gen):
    TOOL_VERIFY_PROMPT = """"You will be given:
1) A user question, and  
2) A reply generated by a language model.

Your task is to determine whether the reply is a valid answer to the user's question.

# Evaluation Rules:

Return **False** if **any** of the following conditions are true:
- The reply does not attempt to answer the user's question.
- The reply asks a follow-up or clarifying question instead of providing an answer.
- The reply does not address or perform the actions, requirements, or intent stated in the question.

Return **True** only if the reply directly and adequately answers the user's question and aligns with the requested actions or intent. You must think/reason in 3 sentences.

# Response Format:

Respond with **only one word**, exactly as shown below:
[True/False]
"""

    # def chat_with_ollama(example):
    messages = [
        {"role": "system", "content": TOOL_VERIFY_PROMPT},
        {"role": "user", "content": llm_gen}
    ]

    # think, response = get_llm_response(messages, think=True, n_tokens=192)
    think, response = get_llm_response(messages, think=False)
    return response.strip().lower() == 'true'


def scorer(response, eval_func, question):
    results = []
    for ef in eval_func:
        code_string = f"{ef}\n\nresponse = '{response}'\n\nprint(evaluate(response))"
        try:
            result = docker_sandbox.run_code(code_string).lower().strip() == 'true'
        except Exception as E:
            print("Exception:", E)
            result = False
        if result:
            prompt = f"# User Question:\n{question}\n\n# Language Model Reply:\n{response}"
            try:
                res =  answer_validate(prompt)
                result = res and result
            except Exception as E:
                print("Exception:", E)
                result = False
        results.append(result)
    return all(results)


def autoif_ds(tokenizer, prompt_token_len):
    dataset = load_dataset("Post-training-Data-Flywheel/AutoIF-instruct-61k-with-funcs")['train']
    dataset = dataset.map(lambda x: {'eval_funcs': list(set(x['eval_funcs']))})
    dataset = dataset.map(lambda x: {
        'prompt': tokenizer.apply_chat_template(
            x['messages'][:-1],
            add_generation_prompt=True,
            tokenize=False,
            continue_final_message=False,
    )})
    dataset = dataset.remove_columns(['system', 'tools', 'conversation_id'])
    dataset = [d for d in dataset]
    for i in range(len(dataset)):
        dataset[i]['scorer'] = partial(scorer, eval_func=dataset[i]['eval_funcs'], question=dataset[i]['messages'][-1]['content'])
    dataset = list(filter(lambda x: len(tokenizer.encode(x['prompt'])) <= prompt_token_len, dataset))
    return dataset


if __name__ == '__main__':
    import json
    from transformers import AutoModelForCausalLM, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained("quwsarohi/NanoAgent-135M")

    ds = autoif(tokenizer, 256)
    print(len(ds))
    # print(json.dumps(ds[10]))

    print(ds[10]['eval_funcs'])

    print(ds[10]['scorer'](response=ds[10]['messages'][-1]['content']))
    print(ds[120]['scorer'](response=ds[10]['messages'][-1]['content']))